# Generated by Django 4.2 on 2025-12-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_bg', models.CharField(default='radial-gradient(#fff, #ffd6d6)', max_length=255)),
                ('banner_heading', models.CharField(default='Give Your Workout A New Style!', max_length=255)),
                ('banner_text', models.TextField(default="Success isn't always about greatness...")),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='theme/')),
                ('button_color', models.CharField(default='#ff523b', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Theme Settings',
            },
        ),
    ]
