# Generated by Django 4.2 on 2026-01-29 08:10

from django.db import migrations, models
import django.db.models.deletion


def create_categories_and_map(apps, schema_editor):
    """Create Category objects from the existing string category values in products"""
    Product = apps.get_model('products', 'Product')
    Category = apps.get_model('products', 'Category')
    
    # Get unique category strings from existing products
    existing_categories = Product.objects.values_list('category', flat=True).distinct()
    
    # Map of old string values to new category data
    category_data = {
        'boots': {'name': 'Football Boots', 'sizes': '5,6,7,8,9'},
        'jersey': {'name': 'Jersey', 'sizes': 'S,M,L,XL,XXL'},
        'shorts': {'name': 'Shorts', 'sizes': 'Free Size'},
        'socks': {'name': 'Socks', 'sizes': 'Free Size'},
        'other': {'name': 'Other', 'sizes': ''},
    }
    
    # Create categories
    category_map = {}
    for old_value in existing_categories:
        if old_value and old_value in category_data:
            data = category_data[old_value]
            cat, created = Category.objects.get_or_create(
                name=data['name'],
                defaults={'sizes': data['sizes']}
            )
            category_map[old_value] = cat.id
    
    # Store mapping in a temporary way - we'll update after the field is added
    return category_map


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sizes',
            field=models.TextField(blank=True, help_text='Enter sizes separated by commas (e.g., S,M,L,XL or 5,6,7,8,9 or Free Size)'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category'),
        ),
    ]


