# Generated by Django 4.2 on 2026-01-29 08:15

from django.db import migrations


def populate_categories(apps, schema_editor):
    """Ensure all categories have sizes and all products have a category assigned"""
    Product = apps.get_model('products', 'Product')
    Category = apps.get_model('products', 'Category')
    
    # Add sizes to existing categories if they don't have them
    size_mapping = {
        'Football Boots': '5,6,7,8,9',
        'Jersey': 'S,M,L,XL,XXL',
        'Shorts': 'Free Size',
        'Socks': 'Free Size',
        'Other': '',
    }
    
    for name, sizes in size_mapping.items():
        Category.objects.filter(name=name).update(sizes=sizes)
    
    # Set any products without a category to 'Other'
    other_cats = Category.objects.filter(name='Other')
    if other_cats.exists():
        other_cat = other_cats.first()
        Product.objects.filter(category__isnull=True).update(category=other_cat)


def reverse_populate(apps, schema_editor):
    """No reverse needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_sizes_alter_product_category'),
    ]

    operations = [
        migrations.RunPython(populate_categories, reverse_populate),
    ]


